### ISSUE TITLE
 H4Plugins

### ISSUE THREAD

**Issue by yoggiland** [HamzaHajeir/H4Plugins_Env#1]
Sorry to hear that Phil Bowles has passed away. These libraries sounded so promising, what state are the libraries currently in and what will happen to them, is there any further for them?

**Comment by HamzaHajeir** [comment]
Hi @yoggiland, sorry for not responding earlier, but I've not been notified for your message and I don't regularily check github repos.

We've tried to get his paperworks, but sadly there's no progress in that, it's better to communicate over the [facebook group](https://www.facebook.com/groups/h4plugins)
