### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by brodrigz** [HamzaHajeir/H4Plugins_Env#2]
I'm trying to get ArmadilloHTTP to work with HTTPS requests on my esp32, I tried your pio environment, but I'm getting a linker error on build, I've attempted the following example:

#include "Arduino.h"
#include "ArmadilloHTTP.h"
#include "WiFi.h"
#include <Ticker.h>
```

void ArmadilloError(int e, int info)
{
  switch (e)
  {
    //
    //   From Aardvark, deriving from TCP server handling
    //
  // case H4AT_TCP_DISCONNECTED:
  //     Serial.printf("ERROR: NOT CONNECTED info=%d\n", info);
  //     break;
  // case VARK_TCP_UNHANDLED:
  //     Serial.printf("ERROR: UNHANDLED TCP ERROR info=%d\n", info);
  //     break;
  // case VARK_TLS_BAD_FINGERPRINT:
  //     Serial.printf("ERROR: TLS_BAD_FINGERPRINT info=%d\n", info);
  //     break;
  // case VARK_TLS_NO_FINGERPRINT:
  //     Serial.printf("WARNING: NO FINGERPRINT, running insecure\n");
  //     break;
  // case VARK_TLS_NO_SSL:
  //     Serial.printf("ERROR: secure https:// requested, NO SSL COMPILED-IN: READ DOCS!\n");
  //     break;
  // case VARK_TLS_UNWANTED_FINGERPRINT:
  //     Serial.printf("WARNING: FINGERPRINT provided, insecure http:// given\n");
  //     break;
  // case VARK_INPUT_TOO_BIG: //
  //     Serial.printf("ERROR: RX msg(%d) that would 'break the bank'\n", info);
  //     break;
  //
  //   From Armadillo itself, deriving from the HTTP protocol
  //
  case ARMA_ERROR_BUSY:
    Serial.printf("ARMA:request already in-flight\n");
    break;
  case ARMA_ERROR_HTTP:
    Serial.printf("ARMA:HTTP_ERROR %d\n", info);
    break;
  case ARMA_ERROR_TOO_BIG:
    Serial.printf("ARMA:RX DATA TOO BIG %d\n", info);
    break;
  case ARMA_ERROR_TCP_UNHANDLED:
    Serial.printf("ARMA:UNHANDLED TCP ERROR %d\n", info);
    break;
  case ARMA_ERROR_VERB_PROHIBITED:
    Serial.printf("ARMA:VERB NOT ALLOWED\n");
    break;
  case ARMA_ERROR_CHUNKED:
    Serial.printf("ARMA: Cannot handle xfer chunked (yet)\n");
    break;
  default:
    Serial.printf("UNKNOWN ERROR: %d extra info %d\n", e, info);
    break;
  }
}
//

// 10s
#define HEARTBEAT_INTERVAL 10

ArmadilloHTTP aClient;
Ticker ticker1;
const char *ssid = "ssid";
const char *password = "pass";

// Fixed URL and payload for stress testing
const char *endpoint = "https://site.com/endpoint";

H4AT_NVP_MAP payload = {
    {"Key1", "Val1"},
    {"Key2", "Val2"},
    {"Key3", "Val3"}};
    
void responseHandler(ARMA_HTTP_REPLY r)
{ // r is a struct will all the reply fields you might need
  Serial.printf("\nRaw Data\n");
  dumphex(r.data, r.length);
}

void heartBeatPrint()
{
  static int num = 1;

  if (WiFi.status() == WL_CONNECTED)
    Serial.println("WiFi Heartbeat: " + String(WiFi.RSSI())); // H means connected to WiFi
  else
    Serial.println(F("WiFi Disconnected!")); // F means not connected to WiFi
}

void setup()
{
  // Init Serial
  Serial.begin(115200);
  while (!Serial && millis() < 5000)
    ;
  delay(200);

  // Init Wifi
  WiFi.mode(WIFI_STA);
  // WiFi.setAutoConnect(true);
  WiFi.begin(ssid, password);
  WiFi.waitForConnectResult();
  Serial.println("Connected to wifi");
  delay(1000);

  // Execute request
  Serial.println("Executing request");
  aClient.onHTTPerror(ArmadilloError);
  aClient.POST(endpoint, payload, responseHandler); // <--- Yup, that's pretty much it!

  // Attach heartbeat ticker
  ticker1.attach(HEARTBEAT_INTERVAL, heartBeatPrint);
}

void loop()
{
}
```

And got build error:```

Processing esp32doit-devkit-v1 (board: esp32doit-devkit-v1; platform: https://github.com/tasmota/platform-espressif32/releases/download/2024.08.10/platform-espressif32.zip; framework: arduino)   
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html
PLATFORM: Espressif 32 (2024.8.10) > DOIT ESP32 DEVKIT V1
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)   
PACKAGES:
 - framework-arduinoespressif32 @ 3.0.3+sha.b6b4727
 - framework-arduinoespressif32-libs @ 5.1.0+sha.b6b4727
 - tool-esptoolpy @ 4.7.6
 - tool-mklittlefs @ 3.2.0
 - tool-riscv32-esp-elf-gdb @ 11.2.0+20220823
 - tool-xtensa-esp-elf-gdb @ 11.2.0+20230208
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing AsyncUDP
Warning! Could not find the package with 'AsyncUDP' requirements for your system 'windows_amd64'
Found 43 compatible libraries
Scanning dependencies...
Dependency Graph
|-- H4 @ 4.0.7+sha.5be2351
|-- H4Tools @ 0.0.13+sha.4a2d7f8
|-- H4AsyncTCP @ 0.0.23+sha.906ed12
|-- ArmadilloHTTP @ 0.1.8+sha.00dca57
|-- LittleFS @ 3.0.3
|-- WiFi @ 3.0.3
|-- Ticker @ 3.0.3
Building in release mode
Linking .pio\build\esp32doit-devkit-v1\firmware.elf
c:/users/myUser/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32doit-devkit-v1\lib438\libH4.a(H4.cpp.o): in function `setup()':
C:\Users\myUser\Documents\PlatformIO\Projects\H4Test/.pio/libdeps/esp32doit-devkit-v1/H4/src/H4.cpp:356: multiple definition of `setup()'; .pio\build\esp32doit-devkit-v1\src\main.cpp.o:C:\Users\myUser\Documents\PlatformIO\Projects\H4Test/src/main.cpp:104: first defined here
c:/users/myUser/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32doit-devkit-v1\lib438\libH4.a(H4.cpp.o): in function `loop()':
C:\Users\myUser\Documents\PlatformIO\Projects\H4Test/.pio/libdeps/esp32doit-devkit-v1/H4/src/H4.cpp:362: multiple definition of `loop()'; .pio\build\esp32doit-devkit-v1\src\main.cpp.o:C:\Users\myUser\Documents\PlatformIO\Projects\H4Test/src/main.cpp:127: first defined here
c:/users/myUser/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32doit-devkit-v1\lib438\libH4.a(H4.cpp.o):(.literal._ZN4task9cleardownEm+0x0): undefined reference to `h4'
c:/users/myUser/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32doit-devkit-v1\lib438\libH4.a(H4.cpp.o):(.literal._ZN4task9cleardownEm+0x4): undefined reference to `h4'
c:/users/myUser/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32doit-devkit-v1\lib438\libH4.a(H4.cpp.o):(.literal._ZN4task9cleardownEm+0x8): undefined reference to `h4'
c:/users/myUser/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32doit-devkit-v1\lib428\libArmadilloHTTP.a(ArmadilloHTTP.cpp.o):(.literal._ZNSt17_Function_handlerIFvvEZN13ArmadilloHTTP8_prepareEmRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_St8functionIFv21ArmadilloHTTPresponseEERKSt13unordered_mapIS7_S7_St4hashIS7_ESt8equal_toIS7_ESaISt4pairIS8_S7_EEEEUlvE2_E9_M_invokeERKSt9_Any_data+0x8): undefined reference to `h4'
c:/users/myUser/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32doit-devkit-v1\libb34\libH4Tools.a(mbx.cpp.o):(.literal._ZN3mbx5clearEPh+0x0): undefined reference to `mbx::pool'
c:/users/myUser/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32doit-devkit-v1\libb34\libH4Tools.a(mbx.cpp.o):(.literal._ZN3mbx5clearEPh+0x4): undefined reference to `mbx::pool'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32doit-devkit-v1\firmware.elf] Error 1
=================================================================================== [FAILED] Took 23.28 seconds ===================================================================================

Environment          Status    Duration
-------------------  --------  ------------
esp32doit-devkit-v1  FAILED    00:00:23.276
```

**Comment by HamzaHajeir** [comment]
Hi @sacalata 

Please use [this example of ArmadilloHTTP](https://github.com/HamzaHajeir/ArmadilloHTTP/blob/master/examples/ArmadilloMultiRequests/ArmadilloMultiRequests.ino) as a starting point, haven't updated the others, yet.

Needs to remove just some extra code that to manage multiple requests.

Per mbx::pool, its definition was left in H4AsyncMQTT repo sources, so you'll need to add it back in platformio.ini. 

The other temporary solution is to insert this into main.cpp, until the fix gets applied to this repo:
```
#include <unordered_set>
#include <mbx.h>
std::unordered_set	<uint8_t*> mbx::pool;
```

**Comment by HamzaHajeir** [comment]
Per the linking error the mbx::pool, you can use the uploaded repository correctly now.
